const flashcards = [
        { dzongkha: "༡", pronunciation: "ci", group: "number", meaning: "one", category: "numeral" },
        { dzongkha: "༢", pronunciation: "nyi", group: "number", meaning: "two", category: "numeral" },
        { dzongkha: "༣", pronunciation: "sum", group: "number", meaning: "three", category: "numeral" },
        { dzongkha: "༤", pronunciation: "zhi", group: "number", meaning: "four", category: "numeral" },
        { dzongkha: "༥", pronunciation: "nga", group: "number", meaning: "five", category: "numeral" },
        { dzongkha: "༦", pronunciation: "du", alternate: "dru", group: "number", meaning: "six", category: "numeral" },
        { dzongkha: "༧", pronunciation: "dun", group: "number", meaning: "seven", category: "numeral" },
        { dzongkha: "༨", pronunciation: "ghe", group: "number", meaning: "eight", category: "numeral" },
        { dzongkha: "༩", pronunciation: "gu", group: "number", meaning: "nine", category: "numeral" },
        { dzongkha: "༡༠", pronunciation: "cuthâm", group: "number", meaning: "ten", category: "numeral" },
        { dzongkha: "ཀ", pronunciation: "ka", group: "consonant", example: "kite", aspiration: "no", voiced: "no", place: "velar", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཁ", pronunciation: "kha", group: "consonant", example: "khaki", aspiration: "yes", voiced: "no", place: "velar", manner: "plosive", tone: "neutral" },
        { dzongkha: "ག", pronunciation: "ga", group: "consonant", example: "go", aspiration: "no", voiced: "yes", place: "velar", manner: "plosive", tone: "neutral" },
        { dzongkha: "ང", pronunciation: "nga", group: "consonant", example: "song", aspiration: "no", voiced: "yes", place: "velar", manner: "nasal", tone: "low" },
        { dzongkha: "ཅ", pronunciation: "cha", group: "consonant", example: "chop", aspiration: "no", voiced: "no", place: "palatal", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཆ", pronunciation: "chha", group: "consonant", example: "church", aspiration: "yes", voiced: "no", place: "palatal", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཇ", pronunciation: "ja", group: "consonant", example: "jump", aspiration: "no", voiced: "yes", place: "palatal", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཉ", pronunciation: "nya", group: "consonant", example: "canyon", aspiration: "no", voiced: "yes", place: "palatal", manner: "nasal", tone: "low" },
        { dzongkha: "ཏ", pronunciation: "ta", group: "consonant", example: "top", aspiration: "no", voiced: "no", place: "dental", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཐ", pronunciation: "tha", group: "consonant", example: "Thai", aspiration: "yes", voiced: "no", place: "dental", manner: "plosive", tone: "neutral" },
        { dzongkha: "ད", pronunciation: "da", group: "consonant", example: "dog", aspiration: "no", voiced: "yes", place: "dental", manner: "plosive", tone: "neutral" },
        { dzongkha: "ན", pronunciation: "na", group: "consonant", example: "net", aspiration: "no", voiced: "yes", place: "dental", manner: "nasal", tone: "low" },
        { dzongkha: "པ", pronunciation: "pa", group: "consonant", example: "pat", aspiration: "no", voiced: "no", place: "labial", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཕ", pronunciation: "pha", group: "consonant", example: "pharmacy", aspiration: "yes", voiced: "no", place: "labial", manner: "plosive", tone: "neutral" },
        { dzongkha: "བ", pronunciation: "ba", group: "consonant", example: "bat", aspiration: "no", voiced: "yes", place: "labial", manner: "plosive", tone: "neutral" },
        { dzongkha: "མ", pronunciation: "ma", group: "consonant", example: "map", aspiration: "no", voiced: "yes", place: "labial", manner: "nasal", tone: "low" },
        { dzongkha: "ཙ", pronunciation: "tsa", group: "consonant", example: "pizza", aspiration: "no", voiced: "no", place: "alveolar", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཚ", pronunciation: "tsha", group: "consonant", example: "tsunami", aspiration: "yes", voiced: "no", place: "alveolar", manner: "plosive", tone: "neutral" },        
        { dzongkha: "ཛ", pronunciation: "dza", group: "consonant", example: "zebra", aspiration: "no", voiced: "yes", place: "alveolar", manner: "plosive", tone: "neutral" },
        { dzongkha: "ཝ", pronunciation: "wa", group: "consonant", example: "water", aspiration: "no", voiced: "yes", place: "labial", manner: "approximant", tone: "neutral" },
        { dzongkha: "ཞ", pronunciation: "zha", group: "consonant", example: "measure", aspiration: "no", voiced: "yes", place: "postalveolar", manner: "fricative", tone: "neutral" },
        { dzongkha: "ཟ", pronunciation: "za", group: "consonant", example: "zoo", aspiration: "no", voiced: "yes", place: "alveolar", manner: "fricative", tone: "neutral" },
        { dzongkha: "འ", pronunciation: "'a", group: "consonant", example: "aha", aspiration: "no", voiced: "yes", place: "glottal", manner: "approximant", tone: "neutral" },
        { dzongkha: "ཡ", pronunciation: "ya", group: "consonant", example: "yes", aspiration: "no", voiced: "yes", place: "palatal", manner: "approximant", tone: "neutral" },
        { dzongkha: "ར", pronunciation: "ra", group: "consonant", example: "rat", aspiration: "no", voiced: "yes", place: "alveolar", manner: "trill", tone: "neutral" },
        { dzongkha: "ལ", pronunciation: "la", group: "consonant", example: "lamp", aspiration: "no", voiced: "yes", place: "alveolar", manner: "approximant", tone: "neutral" },
        { dzongkha: "ཤ", pronunciation: "sha", group: "consonant", example: "shy", aspiration: "no", voiced: "no", place: "postalveolar", manner: "fricative", tone: "neutral" },
        { dzongkha: "ས", pronunciation: "sa", group: "consonant", example: "sun", aspiration: "no", voiced: "no", place: "alveolar", manner: "fricative", tone: "neutral" },
        { dzongkha: "ཧ", pronunciation: "ha", group: "consonant", example: "hat", aspiration: "yes", voiced: "no", place: "glottal", manner: "fricative", tone: "neutral" },
        { dzongkha: "ཨ", pronunciation: "a", group: "vowel", example: "father", aspiration: "no", voiced: "yes", place: "glottal", manner: "approximant", tone: "neutral" },
        { dzongkha: "ཨི", pronunciation: "i", group: "vowel", example: "ski", aspiration: "no", voiced: "yes", place: "glottal", manner: "vowel", tone: "neutral" },
        { dzongkha: "ཨུ", pronunciation: "u", group: "vowel", example: "food", aspiration: "no", voiced: "yes", place: "glottal", manner: "vowel", tone: "neutral" },
        { dzongkha: "ཨེ", pronunciation: "e", group: "vowel", example: "bed", aspiration: "no", voiced: "yes", place: "glottal", manner: "vowel", tone: "neutral" },
        { dzongkha: "ཨོ", pronunciation: "o", group: "vowel", example: "go", aspiration: "no", voiced: "yes", place: "glottal", manner: "vowel", tone: "neutral" }
    ];
  